version: "3.8"
services:
  remixide:
    image: remix
    build: .
    container_name: remixide
    tty: true
    volumes: 
      - ./contracts:/usr/contracts
    ports: 
      - 8080:8080
      - 65520:65520
